# Generated by Django 5.1.1 on 2025-05-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_item_growth_period_item_is_seed_item_sun_condition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
