# Generated by Django 5.1.1 on 2025-05-14 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0003_item_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="is_seed",
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("SEED", "Seed"),
                    ("FERTILIZER", "Fertilizer"),
                    ("PESTICIDE", "Pesticide"),
                    ("PLANT", "Plant"),
                ],
                default="SEED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="plant_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plant_items",
                to="item.item",
            ),
        ),
    ]
