# Generated by Django 5.1.1 on 2025-05-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0005_alter_item_plant_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
