# Generated by Django 5.1.1 on 2025-05-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0002_garden_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="garden",
            name="status",
            field=models.CharField(
                choices=[("GROWING", "Growing"), ("HARVESTABLE", "Harvestable")],
                max_length=100,
            ),
        ),
    ]
