# Generated by Django 5.1.1 on 2024-12-08 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
    ]
