# Generated by Django 5.1.1 on 2025-04-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_remove_user_address_remove_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_tier",
            field=models.CharField(default="normal", max_length=100),
        ),
    ]
