# Generated by Django 5.1.1 on 2025-05-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="caring_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WATERING", "Watering"),
                    ("FERTILIZING", "Fertilizing"),
                    ("HARVESTING", "Harvesting"),
                    ("GROWING", "Growing"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
