# Generated by Django 5.1.1 on 2025-05-14 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0003_alter_garden_status"),
        ("history", "0002_history_caring_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="garden_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="garden.garden",
            ),
        ),
    ]
